-- =====================================================
-- MIGRATION: Add short_name to Master Data Tables
-- Purpose: Support manual editable short names while keeping auto-generate as default
-- =====================================================

-- Step 1: Add short_name column to all master data tables
ALTER TABLE categories ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE main_products ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE variants ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE specifications ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE sizes ADD COLUMN IF NOT EXISTS short_name TEXT;
ALTER TABLE units ADD COLUMN IF NOT EXISTS short_name TEXT;

-- Step 2: Create function to generate short name (PostgreSQL version)
-- This replicates the TypeScript generateShortName() logic
CREATE OR REPLACE FUNCTION generate_short_name(p_name TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  v_short_name TEXT;
  v_words TEXT[];
  v_word TEXT;
  v_result TEXT := '';
BEGIN
  -- Handle empty input
  IF p_name IS NULL OR LENGTH(TRIM(p_name)) = 0 THEN
    RETURN NULL;
  END IF;
  
  -- Remove common words and clean the string
  v_short_name := UPPER(TRIM(p_name));
  v_short_name := REGEXP_REPLACE(v_short_name, '\b(DAN|ATAU|YANG|DENGAN|KE|DARI|DI|UNTUK|THE|AND|OR|OF|TO|FROM|IN|FOR)\b', '', 'gi');
  
  -- Split by spaces and take first letter of each word
  v_words := STRING_TO_ARRAY(TRIM(v_short_name), ' ');
  
  FOREACH v_word IN ARRAY v_words
  LOOP
    IF LENGTH(TRIM(v_word)) > 0 THEN
      v_result := v_result || LEFT(TRIM(v_word), 1);
    END IF;
  END LOOP;
  
  -- If result is too short or empty, take first 3 characters
  IF LENGTH(v_result) = 0 THEN
    v_result := UPPER(LEFT(REGEXP_REPLACE(p_name, '[^A-Za-z0-9]', '', 'g'), 3));
  END IF;
  
  RETURN v_result;
END;
$$;

-- Step 3: Populate short_name for existing data using auto-generate algorithm
UPDATE categories SET short_name = generate_short_name(name) WHERE short_name IS NULL;
UPDATE brands SET short_name = generate_short_name(name) WHERE short_name IS NULL;
UPDATE main_products SET short_name = generate_short_name(name) WHERE short_name IS NULL;
UPDATE variants SET short_name = generate_short_name(name) WHERE short_name IS NULL;
UPDATE specifications SET short_name = generate_short_name(name) WHERE short_name IS NULL;
UPDATE sizes SET short_name = generate_short_name(name) WHERE short_name IS NULL;
UPDATE units SET short_name = generate_short_name(name) WHERE short_name IS NULL;

-- Step 4: Add comments for documentation
COMMENT ON COLUMN categories.short_name IS 'Short name for the category. Auto-generated by default but can be manually edited.';
COMMENT ON COLUMN brands.short_name IS 'Short name for the brand. Auto-generated by default but can be manually edited.';
COMMENT ON COLUMN main_products.short_name IS 'Short name for the main product. Auto-generated by default but can be manually edited.';
COMMENT ON COLUMN variants.short_name IS 'Short name for the variant. Auto-generated by default but can be manually edited.';
COMMENT ON COLUMN specifications.short_name IS 'Short name for the specification. Auto-generated by default but can be manually edited.';
COMMENT ON COLUMN sizes.short_name IS 'Short name for the size. Auto-generated by default but can be manually edited.';
COMMENT ON COLUMN units.short_name IS 'Short name for the unit. Auto-generated by default but can be manually edited.';

COMMENT ON FUNCTION generate_short_name(TEXT) IS 'Generates short name from full name. Used as default suggestion when creating new master data.';

-- Step 5: Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_categories_short_name ON categories(short_name);
CREATE INDEX IF NOT EXISTS idx_brands_short_name ON brands(short_name);
CREATE INDEX IF NOT EXISTS idx_main_products_short_name ON main_products(short_name);
CREATE INDEX IF NOT EXISTS idx_variants_short_name ON variants(short_name);
CREATE INDEX IF NOT EXISTS idx_specifications_short_name ON specifications(short_name);
CREATE INDEX IF NOT EXISTS idx_sizes_short_name ON sizes(short_name);
CREATE INDEX IF NOT EXISTS idx_units_short_name ON units(short_name);

-- =====================================================
-- VERIFICATION QUERIES (Optional - for testing)
-- =====================================================

-- Check all tables have short_name populated
-- SELECT 'categories' as table_name, COUNT(*) as total, COUNT(short_name) as with_short_name FROM categories
-- UNION ALL
-- SELECT 'brands', COUNT(*), COUNT(short_name) FROM brands
-- UNION ALL
-- SELECT 'main_products', COUNT(*), COUNT(short_name) FROM main_products
-- UNION ALL
-- SELECT 'variants', COUNT(*), COUNT(short_name) FROM variants
-- UNION ALL
-- SELECT 'specifications', COUNT(*), COUNT(short_name) FROM specifications
-- UNION ALL
-- SELECT 'sizes', COUNT(*), COUNT(short_name) FROM sizes
-- UNION ALL
-- SELECT 'units', COUNT(*), COUNT(short_name) FROM units;

-- Test generate_short_name function
-- SELECT generate_short_name('Cat Kayu dan Besi');  -- Expected: CKB
-- SELECT generate_short_name('Gloss Super White');  -- Expected: GSW
-- SELECT generate_short_name('0,9 Liter');          -- Expected: 09L
