-- Migration 030: Auto Generate Product Names Master Tables

-- 1. Create Main Products Table
CREATE TABLE IF NOT EXISTS main_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(store_id, name)
);

-- 2. Create Variants Table
CREATE TABLE IF NOT EXISTS variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(store_id, name)
);

-- 3. Create Specifications Table
CREATE TABLE IF NOT EXISTS specifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(store_id, name)
);

-- 4. Create Sizes Table
CREATE TABLE IF NOT EXISTS sizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(store_id, name)
);

-- 5. Alter Products Table
ALTER TABLE products 
  ADD COLUMN IF NOT EXISTS main_product_id BIGINT REFERENCES main_products(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS variant_id BIGINT REFERENCES variants(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS specification_id BIGINT REFERENCES specifications(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS size_id BIGINT REFERENCES sizes(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS short_name TEXT;

-- 6. Enable RLS
ALTER TABLE main_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE specifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE sizes ENABLE ROW LEVEL SECURITY;

-- 7. Add RLS Policies
-- Main Products
CREATE POLICY "Enable read access for users based on store_id" ON main_products FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON main_products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON main_products FOR UPDATE USING (true);
CREATE POLICY "Enable delete for authenticated users only" ON main_products FOR DELETE USING (true);

-- Variants
CREATE POLICY "Enable read access for users based on store_id" ON variants FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON variants FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON variants FOR UPDATE USING (true);
CREATE POLICY "Enable delete for authenticated users only" ON variants FOR DELETE USING (true);

-- Specifications
CREATE POLICY "Enable read access for users based on store_id" ON specifications FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON specifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON specifications FOR UPDATE USING (true);
CREATE POLICY "Enable delete for authenticated users only" ON specifications FOR DELETE USING (true);

-- Sizes
CREATE POLICY "Enable read access for users based on store_id" ON sizes FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON sizes FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only" ON sizes FOR UPDATE USING (true);
CREATE POLICY "Enable delete for authenticated users only" ON sizes FOR DELETE USING (true);
